- name: set timezone
  command: timedatectl set-timezone Asia/Tokyo

- name: add epel-release
  yum:
    name: epel-release
    state: installed

- name: add remi-release
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: installed

- name: add PHP Extension library
  yum: name={{ item }} state=installed enablerepo=epel,remi,remi-php56
  with_items:
    - libtidy
    - libmcrypt

- name: install base
  yum: name={{ item }} state=installed
  with_items:
    - wget
    - vim
    - gcc
    - libxml2
    - libxml2-devel
    - curl-devel
    - readline-devel
    - libxslt-devel
    - giflib-devel
    - openssl
    - openssl-devel
    - openssh-clients
    - crontabs

- name: selinux off
  selinux: state=disabled